INFO     Logger:page.py:120 Page.wait_until_stable() - Page wait until driver stable
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd1de0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd2020>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd25f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:120 Page.wait_until_stable() - Page wait until driver stable
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd28f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd2b30>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd09a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:120 Page.wait_until_stable() - Page wait until driver stable
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd0eb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd0880>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd0df0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:120 Page.wait_until_stable() - Page wait until driver stable
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd3e20>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773abd3fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f773aa78880>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:120 Page.wait_until_stable() - Page wait until driver stable
INFO     Logger:page.py:206 Page.maximize_window() - Maximize browser window
INFO     Logger:page.py:54 User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
INFO     Logger:page.py:106 Page.visit() - Get URL: 'https://next.4zida.rs'
INFO     Logger:page.py:108 Client window width: 393, window height: 873
INFO     Logger:page.py:249 The title of the page is 'Pretraga Nekretnina za Prodaju i Izdavanje · 4zida'
INFO     Logger:page.py:163 Page.find_xpath() - Get the elements with xpath: '//h1'
INFO     Logger:component.py:60 Actual headers text: ['Pronađi idealnu nekretninu za sebe!']
INFO     Logger:page.py:136 Page.get_xpath() - Get the element with xpath: '//div[@test-data="search-form"]'
INFO     Logger:page.py:199 Page.screenshot() - Save screenshot to: 'screenshots/test_home_page2024-02-25T080749.png'
WARNING  Logger:conftest.py:47 Browser console logs: []
INFO     Logger:page.py:191 Page.quit() - Quit page and close all windows from the browser session