INFO     Logger:page.py:121 Page.wait_until_stable() - Page wait until driver stable
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d23e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d21a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d1f30>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:121 Page.wait_until_stable() - Page wait until driver stable
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d35e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d2cb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d2c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:121 Page.wait_until_stable() - Page wait until driver stable
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d0a90>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d0be0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d0c70>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:121 Page.wait_until_stable() - Page wait until driver stable
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d3e80>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a19d3fd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f93a187c7f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:121 Page.wait_until_stable() - Page wait until driver stable
INFO     Logger:page.py:207 Page.maximize_window() - Maximize browser window
INFO     Logger:page.py:54 User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
INFO     Logger:page.py:106 Page.visit() - Get URL: 'https://next.4zida.rs'
INFO     Logger:page.py:109 Client window width: 393, window height: 873
INFO     Logger:page.py:250 The title of the page is 'Pretraga Nekretnina za Prodaju i Izdavanje · 4zida'
INFO     Logger:page.py:164 Page.find_xpath() - Get the elements with xpath: '//h1'
INFO     Logger:component.py:60 Actual headers text: ['Pronađi idealnu nekretninu za sebe!']
INFO     Logger:page.py:137 Page.get_xpath() - Get the element with xpath: '//div[@test-data="search-form"]'
INFO     Logger:page.py:200 Page.screenshot() - Save screenshot to: 'screenshots/test_home_page2024-02-28T112900.png'
INFO     Logger:page.py:192 Page.quit() - Quit page and close all windows from the browser session